---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '\.Rd' # sometimes roxygen fails to generate EOF blank line.
      - id: file-contents-sorter
        files: '^\.Rbuildignore$'
